name: Pull Request related comments
on:
  pull_request_target:
    types:
      - opened
  
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on Opening Pull Request
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.APIVerse_SECRET }}
          script: |
            const {owner, repo, number} = context.issue;
            const commentAuthor = context.payload.sender.login;
            const commentBody = `Hey @${ commentAuthor }, Thank you for creating PR! We will review it super soon. üòá‚ù£Ô∏è
            As we continue to evolve and innovate, we encourage you to share your ideas, feedback, and code to help us push the boundaries of what's possible in the world of APIsüöÄ.
            We hope you have followed [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
            Thank you for being an essential part of our community. Together, we'll keep building amazing things!
            Don‚Äôt forget to ‚≠ê our repository!
            Happy Coding!‚ú®
            Will See you soon‚ù£Ô∏è `;
            await github.issues.createComment({owner, repo, issue_number : number, body: commentBody});
            console.log('Commented on PR');
